---
- name: Gather lxc container host facts
  hosts: baremetals
  gather_facts: True

- hosts: all_containers
  vars_files: 
    - defination.yml    
  become: true
  gather_facts: true
  roles:
   - role: lxc_container_create 
     