---
- name: Create base directories
  file:
    path: "{{ item }}"
    state: "directory"
    owner: "root"
    group: "root"
  with_items:
    - /etc/lxc
    - /usr/local/bin
    - /etc/network/interfaces.d
    - /etc/apparmor.d/lxc
    - /usr/share/lxc/templates
    - /openstack
    - /openstack/backup
    - /openstack/log
    - "{{ lxc_container_directory }}"
    - "{{ lxc_container_cache_path }}"
  tags:
    - lxc-directories
    
- name: Install apt packages
  apt:
    pkg: "{{ item }}"
    state: "{{ lxc_hosts_package_state }}"
    default_release: "{{ lxc_default_release | default(omit) }}"
    update_cache: yes
    cache_valid_time: "{{ cache_timeout }}"
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  with_items: "{{ lxc_hosts_distro_packages }}"
  tags:
    - lxc-apt-packages


- name: Install pip packages
  pip:
    name: "{{ lxc_pip_packages }}"
    state: "{{ lxc_hosts_pip_package_state }}"
    extra_args: >-
      {{ (pip_install_upper_constraints is defined) | ternary('--constraint ' + pip_install_upper_constraints | default(''),'') }}
      {{ pip_install_options | default('') }}
  register: install_packages
  until: install_packages|success
  retries: 5
  delay: 2
  tags:
    - lxc-pip-packages
    
- name: Ensure the lxc dnsmasq user exists
  user:
    name: "{{ lxc_net_dnsmasq_user }}"
    comment: "LXC dnsmasq"
    system: "yes"
    shell: "/bin/false"
    home: "/var/lib/lxc"
  tags:
    - lxc-dnsmasq-user

- name: Drop base config file(s)
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ item.owner|default('root') }}"
    group: "{{ item.group|default('root') }}"
    mode: "{{ item.mode|default('0644') }}"
  with_items:
    - { src: lxc-openstack.conf.j2, dest: "/etc/lxc/lxc-openstack.conf" }
    - { src: default.conf.j2, dest: "/etc/lxc/default.conf" }
    - { src: lxc.default.j2, dest: "{{ system_config_dir}}/lxc-net", mode: "0644" }
    - { src: lxc-system-manage.j2, dest: "/usr/local/bin/lxc-system-manage", mode: "0755" }
  tags:
    - lxc-files
    - lxc-config

- name: Drop lxc veth check script
  copy:
    src: "lxc-veth-check.sh"
    dest: "/usr/local/bin/lxc-veth-check"
    owner: "root"
    group: "root"
    mode: "0755"
  tags:
    - lxc-files
    - lxc-config    
    
    